name: BridgedLoopModels
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10
  - pip
  - pytest
  - sphinx
  - numpy
  - pandas
  - networkx
  - xarray
  - chardet
  - jupyterlab
  - napari
  - pyqt
  - pip:
      - open3d==0.18
      - pyvis
      - libigl==2.5.0
      - numba==0.59
      - bpy==4.0.0
      - opencv-python-headless
